export const GET_SMURFS = 'GET_SMURFS';
export const START_GETTING_SMURFS = 'START_GETTING_SMURFS';
export const FINISH_GETTING_SMURFS = 'FINISH_GETTING_SMURFS';
export const START_ADDING_SMURF = 'START_ADDING_SMURF';
export const FINISH_ADDING_SMURF = 'FINISH_ADDING_SMURF';
